### ISSUE TITLE
PrestaShop invalid zip file while installing module

### ISSUE THREAD

**Issue by tomazas** [mijora/omniva-prestahop-1.7#12]
PrestaShop v1.7.6 gives an error while installing module zip downloaded from official site:
https://www.omniva.lt/verslo/siunta/sasajos_el_parduotuvems

> Oops... Upload failed.
> What happened?
> 
> This file does not seem to be a valid module zip

Since current module release versions are outdated the official preffered way to install from master branch zip file does not work out of the box.

**FIX:**
Ensure zip file basename and root folder name inside zip have the same name as main module .php file (e.g. if omnivaltshipping.php is main file, 
then zip filename must be "omnivaltshipping.zip" and root folder has to have name "omnivaltshipping").

**Comment by LithMage** [comment]
Hi, please refer to https://github.com/mijora/omniva-prestahop-1.7/releases page. Each version has zip file attached.
