### ISSUE TITLE
Ask select terminal

### ISSUE THREAD

**Issue by atolodas** [mijora/omniva-prestahop-1.7#13]
Omniva not default shipping, make order. Always show popup as  must select terminal
prestashop 1.7.6.1, theme warehuose, module version v1.1.2

**Comment by gadnis** [comment]
> Omniva not default shipping, make order. Always show popup as must select terminal
> prestashop 1.7.6.1, theme warehuose, module version v1.1.2

@atolodas it is fixed in newest version
