### ISSUE TITLE
Mail Tracking Number to Customer

### ISSUE THREAD

**Issue by gadnis** [mijora/omniva-prestahop-1.7#14]
Hi,
I would like to request a feature for the module. 

Could you add button "send tracking number" in Order page next to the tracking number?

I believe it is possible to create simple prestashop mail template and put there tracking number. I imagine that template should be prestashop mail template, which could be possible to edit using default prestashop template editor.

Or maybe you have a better idea how to inform customer with the tracking number?
Do you have plans to integrate it?
What do you think, when this feature could be added to your module?

**Comment by LithMage** [comment]
Prestashop has in_transit template as well shipped that does exactly that. If you want tracking link in shipped just add {followup} - in_transit already has it.

**Comment by gadnis** [comment]
Perfect! Thank you ;)
