### ISSUE TITLE
PDF margin is to small

### ISSUE THREAD

**Issue by gadnis** [mijora/omniva-prestahop-1.7#16]
Hi,

all pdf stickers is being printed out of margin. 

Is it possible to add extra margin to all pdf stickers?

**Comment by LithMage** [comment]
Can you please attach an example of suck label?

**Comment by gadnis** [comment]
Using google chrome on windows 10.

Video cast:
https://drive.google.com/file/d/1rq2JGuiJZ0FFfKKe5DTx1ZDIxBoXzYcj/view

Result:
![IMG_5001](https://user-images.githubusercontent.com/10948341/72522096-80ae9980-3865-11ea-8609-50cf5cde9cbc.jpg)

PDF:
[854.pdf](https://github.com/mijora/omniva-prestahop-1.7/files/4070957/854.pdf)

**Comment by LithMage** [comment]
if your printing just one label (taking stright of pdf) we cant do much about it, you should set your printer margins accordingly.

**Comment by gadnis** [comment]
Understood. Thanks ;)
