### ISSUE TITLE
Option 'Terminal to Terminal' missing in BO

### ISSUE THREAD

**Issue by gadnis** [mijora/omniva-prestahop-1.7#18]
Hi,

is it possible to add button choose 'terminal to terminal' in adminOrders page? 

Now it is only carrier to terminal possible, so every time when customer choose terminal, we must go online in omniva web to fill the terminal form, or else we will be charged for 'carrier to terminal' option.

**Comment by LithMage** [comment]
Hi this is set in module settings (send off type) and it can be either courier or parcel terminal.

**Comment by gadnis** [comment]
@LithMage but than label is always Terminal to "Option".
 
![Screen Shot 2020-02-26 at 18 58 33](https://user-images.githubusercontent.com/10948341/75368326-3855b300-58ca-11ea-845e-161ac7d0c049.png)

It would be better if merchant could choose pickup point in adminOrders page. Cause now we need to go in module options everytime we decide to change pickup point.

This option would be great:
![Screen Shot 2020-02-26 at 19 06 52](https://user-images.githubusercontent.com/10948341/75368933-317b7000-58cb-11ea-9248-2ba15db887ba.png)

Could you do that?

**Comment by LithMage** [comment]
Thats possible to do as a custom job. Otherwise i can note it as possible future improvement - but no timeframe or even if it would be approved.
