### ISSUE TITLE
locations.json structure - NULL distance to the Parcel machine.

### ISSUE THREAD

**Issue by k0lv** [mijora/omniva-prestahop-1.7#25]
Hello. Probably this is not the module issue, but still wanted to inform you. 
I have found out, that json structure, that is currently available at omniva website, is different, from that what goes with the module installation. I believe that difference of the structure creates a bug, when the distance to parcel machine is shown as null. Thank you.

![omniva_1](https://user-images.githubusercontent.com/59282576/96372413-503ab980-116f-11eb-9aeb-818fc731a9cc.png)
--------------------
![omniva_2](https://user-images.githubusercontent.com/59282576/96372415-5335aa00-116f-11eb-99a2-b8d42100399a.png)
-------------------
[locations.json.zip](https://github.com/mijora/omniva-prestahop-1.7/files/5397717/locations.json.zip)
-------------------
![image](https://user-images.githubusercontent.com/59282576/96407120-5c635d00-11e9-11eb-83b7-2a11dd4bff70.png)

**Comment by markakk** [comment]
Hello,

The list of parcel terminals is installed together with the module, so it may be out of date after installation (list are those day, which was released update of the module was released). After 24 hours from installation, the module will automatically update the list.
