### ISSUE TITLE
Hardcoded C.O.D module

### ISSUE THREAD

**Issue by codingpandaren** [mijora/omniva-prestahop-1.7#27]
COD payment module should be selectable by vendor in Omniva module settings

https://github.com/mijora/omniva-prestahop-1.7/blob/995045354d40651d2216ea1ab06369634b87c260/classes/OrderInfo.php#L26

**Comment by markakk** [comment]
Hello,

We no longer support this module. If updates or improvements are required, please use this module:
https://github.com/mijora/omniva-prestashop-1.6-1.7
